{
  "hash": "e686da9b9bfd870f38c4080211bfe3b8",
  "result": {
    "markdown": "---\ntitle: \"Analyzing College Football\"\nauthor: \"Claudia Robles\"\ndate: \"2023-11-13\"\ncategories: [analysis, code, football, sports]\nimage: \"football.jpg\"\n---\n\n\nCurrently, I am attending the University of Illinois in Urbana-Champaign. Our football team did well during the Fall 22 season, hence I was inspired to look at a data set that was created by a UIUC professor: Professor Wade Fagen-Ulmschneider.\n\nHe has his own personal github:\n\n[wadefagen (Wade Fagen-Ulmschneider) (github.com)](https://github.com/wadefagen)\n\nWhere he has all the data sets he has created.\n\nBeginning of analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.3     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.3     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfootball <- read_csv(\"https://raw.githubusercontent.com/wadefagen/datasets/master/illini-football/illini-football-scores.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(football)\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |         |\n|:------------------------|:--------|\n|Name                     |football |\n|Number of rows           |1284     |\n|Number of columns        |9        |\n|_______________________  |         |\n|Column type frequency:   |         |\n|character                |5        |\n|numeric                  |4        |\n|________________________ |         |\n|Group variables          |None     |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|Date          |         0|           1.0|   8|  10|     0|     1283|          0|\n|Location      |         0|           1.0|   1|  17|     0|       26|          0|\n|Opponent      |         0|           1.0|   3|  22|     0|      137|          0|\n|Result        |         1|           1.0|   1|   1|     0|        3|          0|\n|Note          |      1151|           0.1|   8|  20|     0|       17|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    mean|    sd|   p0|     p25|    p50|     p75| p100|hist  |\n|:-------------|---------:|-------------:|-------:|-----:|----:|-------:|------:|-------:|----:|:-----|\n|Season        |         0|          1.00| 1962.60| 38.06| 1892| 1931.00| 1967.0| 1995.25| 2022|▆▆▆▇▇ |\n|OpponentRank  |      1274|          0.01|   13.50|  7.56|    3|    7.75|   14.5|   19.25|   24|▇▂▅▂▇ |\n|IlliniScore   |         1|          1.00|   18.89| 14.51|    0|    7.00|   16.0|   27.00|   87|▇▅▂▁▁ |\n|OpponentScore |         1|          1.00|   17.89| 14.75|    0|    6.00|   14.0|   27.00|   70|▇▅▂▁▁ |\n:::\n:::\n\n\nFrom the previous code, we can see that we have a total of 1284 rows. This means, this data set contains 1284 rows worth of data from games played by the Fighting Illini football team. Below, I decided to filter by the column name \"Result\" where it says \"W,\" meaning when the team was able to win a game against their opponent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfootball %>%\n  filter(\n    Result == \"W\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 617 × 9\n   Season Date   Location Opponent OpponentRank Result IlliniScore OpponentScore\n    <dbl> <chr>  <chr>    <chr>           <dbl> <chr>        <dbl>         <dbl>\n 1   2022 8/27/… vs.      Wyoming            NA W               30             6\n 2   2022 9/10/… vs.      Virginia           NA W               24             3\n 3   2022 9/22/… vs.      Chattan…           10 W               31             0\n 4   2022 10/1/… @        Wiscons…           NA W               34            10\n 5   2022 10/8/… vs.      Iowa               NA W                9             6\n 6   2022 10/15… vs.      Minneso…           NA W               26            14\n 7   2022 10/29… @        Nebraska           NA W               26             9\n 8   2022 11/26… @        Northwe…            3 W               41             3\n 9   2021 8/28/… vs.      Nebraska           NA W               30            22\n10   2021 10/2/… vs.      Charlot…           NA W               24            14\n# ℹ 607 more rows\n# ℹ 1 more variable: Note <chr>\n```\n:::\n:::\n\n\nWe see that we have a total of 617 rows, which is crazy to me! Our football team has not won a lot of games. Our first few rows are from the Fall 2022 season, so you can see we have been performing better in terms of winning or losing.\n\nWins at Home vs. Away:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfootball %>%\n  filter(Result == \"W\",\n         Location == \"@\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 207 × 9\n   Season Date   Location Opponent OpponentRank Result IlliniScore OpponentScore\n    <dbl> <chr>  <chr>    <chr>           <dbl> <chr>        <dbl>         <dbl>\n 1   2022 10/1/… @        Wiscons…           NA W               34            10\n 2   2022 10/29… @        Nebraska           NA W               26             9\n 3   2022 11/26… @        Northwe…            3 W               41             3\n 4   2021 10/23… @        Penn St…            7 W               20            18\n 5   2021 11/6/… @        Minneso…           20 W               14             6\n 6   2020 11/14… @        Rutgers            NA W               23            20\n 7   2020 11/21… @        Nebraska           NA W               41            23\n 8   2019 9/7/2… @        UConn              NA W               31            23\n 9   2019 10/26… @        Purdue             NA W               24             6\n10   2019 11/9/… @        Michiga…           NA W               37            34\n# ℹ 197 more rows\n# ℹ 1 more variable: Note <chr>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfootball %>%\n  filter(Result == \"W\",\n         Location == \"vs.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 393 × 9\n   Season Date   Location Opponent OpponentRank Result IlliniScore OpponentScore\n    <dbl> <chr>  <chr>    <chr>           <dbl> <chr>        <dbl>         <dbl>\n 1   2022 8/27/… vs.      Wyoming            NA W               30             6\n 2   2022 9/10/… vs.      Virginia           NA W               24             3\n 3   2022 9/22/… vs.      Chattan…           10 W               31             0\n 4   2022 10/8/… vs.      Iowa               NA W                9             6\n 5   2022 10/15… vs.      Minneso…           NA W               26            14\n 6   2021 8/28/… vs.      Nebraska           NA W               30            22\n 7   2021 10/2/… vs.      Charlot…           NA W               24            14\n 8   2021 11/27… vs.      Northwe…           NA W               47            14\n 9   2019 8/31/… vs.      Akron              NA W               42             3\n10   2019 10/19… vs.      Wiscons…           NA W               24            23\n# ℹ 383 more rows\n# ℹ 1 more variable: Note <chr>\n```\n:::\n:::\n\n\nNow I wanted to compare the wins we have at home games vs. the wins we have during away games. From the number of rows (207 for at Home games and 393 for Away games), we see that we have more wins from playing away games!\n\n\n::: {.cell}\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}